import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/common/navbar";
import { ThemeProvider } from "@/providers/theme-provider";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavbarDemo />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
